name: Python Syntax Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # Проверяем, существует ли .venv, если нет - создаем
          if [ ! -d ".venv" ]; then
            python -m venv .venv  # создаем виртуальное окружение
          fi
          source .venv/bin/activate  # активируем виртуальное окружение
          pip install --upgrade pip
          pip install flake8  # Устанавливаем flake8 для проверки синтаксиса
          pip install -r requirements.txt || true  # Устанавливаем зависимости из requirements.txt (если файл есть)

      - name: Check Python syntax
        run: |
          source .venv/bin/activate  # активируем виртуальное окружение
          flake8 .venv/d.py  # проверяем синтаксис файла d.py
